import { calculateNetPrice } from "./pricing";
import type { Product } from "./types";

export const initialProducts: Product[] = [
  {
    id: "prod-macbook-pro-14",
    name: 'MacBook Pro 14"',
    sku: "MBP14M3PRO",
    description: "Laptop Apple z chipem M3 Pro",
    producer: "Apple",
    category: "Komputery",
    features: ["WiFi", "USB-C", "Premium"],
    netPrice: calculateNetPrice(9999, 23),
    grossPrice: 9999,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minCartQuantity: 1,
    maxCartQuantity: 5,
  },
  {
    id: "prod-galaxy-s24-ultra",
    name: "Galaxy S24 Ultra",
    sku: "SGS24U256",
    description: "Flagowy smartfon Samsung",
    producer: "Samsung",
    category: "Telefony",
    features: ["Bluetooth", "WiFi", "Wodoodporny", "Premium"],
    netPrice: calculateNetPrice(6299, 23),
    grossPrice: 6299,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 45,
    minCartQuantity: 1,
    maxCartQuantity: 3,
  },
  {
    id: "prod-sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    sku: "SNWH1000XM5",
    description: "Słuchawki z aktywną redukcją szumów",
    producer: "Sony",
    category: "RTV",
    features: ["Bluetooth", "Bezprzewodowy", "Premium"],
    netPrice: calculateNetPrice(1599, 23),
    grossPrice: 1599,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minCartQuantity: 1,
    maxCartQuantity: 10,
  },
  {
    id: "prod-bosch-serie-6",
    name: "Bosch Serie 6 WAU28P40",
    sku: "BSWAU28P40",
    description: "Pralka wolnostojąca",
    producer: "Bosch",
    category: "AGD",
    features: ["Ekologiczny"],
    netPrice: calculateNetPrice(3299, 23),
    grossPrice: 3299,
    vatRate: 23,
    currency: "PLN",
    isAvailable: false,
    isLimited: true,
    stockQuantity: 0,
    minCartQuantity: 1,
    maxCartQuantity: 1,
  },
  {
    id: "prod-xiaomi-smart-band-8",
    name: "Xiaomi Smart Band 8",
    sku: "XMSB8BLK",
    description: "Opaska sportowa",
    producer: "Xiaomi",
    category: "Akcesoria",
    features: ["Bluetooth", "Wodoodporny"],
    netPrice: calculateNetPrice(179, 23),
    grossPrice: 179,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minCartQuantity: 1,
    maxCartQuantity: 10,
  },
];
